# Интервал между сообщениями в секундах
interval: 60

# Рандомные сообщение (true/false)
random: false

# Звук который будет воспроизводиться при отправке сообщения
sound: BLOCK_NOTE_BLOCK_PLING

# Сообщения к командам
reload-message: "&#008000Конфигурация плагина успешно перезагружена!"
permission-error: "&#FF0000У вас нет прав на выполнение этой команды."
help: "&#008000Используйте: /nautomessages reload"

# Сообщения
# Для цветов можно использовать '§', '&' и '&# - Для HEX цветов.'
# Например: §f, &f и &#FFFFFF
Messages:
  test1: # Уникальный айди сообщения
    - "&#FFFFFFЭто сообщение сделано с помощью" # 1 Строка сообщения
    - "&#FFFFFFплагина NAutoMessages!" # 2 Строка сообщения
  test2:
    - "&#FFFFFFЭто сообщение сделано с помощью"
    - "&#FFFFFFплагина NAutoMessages!"