# Интервал между сообщениями в секундах
interval: 60

# Рандомные сообщение (true/false)
random: false

# Звук который будет воспроизводиться при отправке сообщения
sound: BLOCK_NOTE_BLOCK_PLING

# Сообщения к командам
reload-message: "§aКонфигурация плагина успешно перезагружена!"
permission-error: "§cУ вас нет прав на выполнение этой команды."
help: "§eИспользуйте: /nautomessages reload"

# Сообщения
Messages:
  test1: # Уникальный айди сообщения
    - "§bЭто сообщение сделано с помощью" # 1 Строка сообщения
    - "§aплагина NAutoMessages!" # 2 Строка сообщения
  test2:
    - "§bЭто сообщение сделано с помощью"
    - "§aплагина NAutoMessages!"